# Generated by Django 6.0.2 on 2026-03-24 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_order_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Shipment Pending'), ('preparing', 'Shipment Preparing'), ('ready_to_ship', 'Shipment Ready to Ship'), ('shipped', 'Shipped'), ('in_transit', 'Shipment in Transit'), ('out_for_delivery', 'Shipment out for Delivery'), ('delivered', 'Shipment Delivered'), ('failed', 'Shipment Failed'), ('returned', 'Shipment Returned'), ('cancelled', 'Shipment Cancelled')], db_index=True, max_length=32)),
                ('shipping_method', models.CharField(choices=[('standard', 'Shipping Standard'), ('express', 'Shipping Express'), ('same_day', 'Shipping Same Day'), ('pickup_point', 'Shipping Pickup Point')], db_index=True, default='standard', max_length=32)),
                ('carrier_name', models.CharField(blank=True, max_length=120)),
                ('tracking_code', models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, help_text='Reference used by external carrier or shipping gateway.', max_length=120, null=True)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('estimated_delivery_date', models.DateField(blank=True, db_index=True, null=True)),
                ('delivered_to_name', models.CharField(blank=True, help_text='Optional recipient confirmation name for delivery.', max_length=255)),
                ('is_return_to_sender', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='shipping.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparing_at', models.DateTimeField(blank=True, null=True)),
                ('ready_to_ship_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('in_transit_at', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle', to='shipping.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes are only visible to operational staff.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='shipping.shipment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTrackingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Shipment Pending'), ('preparing', 'Shipment Preparing'), ('ready_to_ship', 'Shipment Ready to Ship'), ('shipped', 'Shipped'), ('in_transit', 'Shipment in Transit'), ('out_for_delivery', 'Shipment out for Delivery'), ('delivered', 'Shipment Delivered'), ('failed', 'Shipment Failed'), ('returned', 'Shipment Returned'), ('cancelled', 'Shipment Cancelled')], max_length=32)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('raw_payload', models.JSONField(blank=True, help_text='Optional original payload from carrier integration.', null=True)),
                ('event_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='shipping.shipment')),
            ],
            options={
                'ordering': ['-event_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['customer', 'created_at'], name='ship_cust_created_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='ship_status_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_code'], name='ship_track_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['estimated_delivery_date'], name='ship_est_deliv_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', 'created_at'], name='shipevent_ship_created'),
        ),
        migrations.AddIndex(
            model_name='shipmentnote',
            index=models.Index(fields=['shipment', 'created_at'], name='shipnote_ship_created'),
        ),
        migrations.AddIndex(
            model_name='shipmenttrackingupdate',
            index=models.Index(fields=['shipment', 'event_at'], name='shiptrack_ship_event_idx'),
        ),
    ]
