# Generated by Django 6.0.2 on 2026-03-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
