# Generated by Django 6.0.2 on 2026-03-14 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlifecycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlifecycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
