# Generated by Django 6.0.2 on 2026-03-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderlifecycle_created_at_orderlifecycle_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('authorized', 'Authorized Payment'), ('captured', 'Captured Payment'), ('failed', 'Failed Payment'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded Payment')], db_index=True, max_length=32),
        ),
    ]
