"use client";

import { ErrorState } from "@/components/feedback/error-state";
import { LoadingState } from "@/components/feedback/loading-state";
import { PageContainer } from "@/components/layout/page-container";
import { PageTitle } from "@/components/layout/page-title";
import { SnapshotTable } from "@/features/analytics/components/snapshot-table";
import { useSnapshots } from "@/features/analytics/hooks/use-snapshots";

export default function AnalyticsSnapshotsPage() {
  const { data, isLoading, isError, refetch } = useSnapshots();

  if (isLoading) {
    return (
      <PageContainer>
        <LoadingState title="Loading analytics snapshots..." />
      </PageContainer>
    );
  }

  if (isError || !data) {
    return (
      <PageContainer>
        <ErrorState
          title="Unable to load analytics snapshots."
          description="Snapshot data is currently unavailable."
          onRetry={() => refetch()}
        />
      </PageContainer>
    );
  }

  return (
    <PageContainer>
      <PageTitle
        eyebrow="Analytics"
        title="Snapshots"
        description="Review materialized analytics snapshots generated by the platform."
      />

      <SnapshotTable snapshots={data.results} />
    </PageContainer>
  );
}