# Generated by Django 6.0.2 on 2026-04-04 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_order_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('pix', 'Pix'), ('bank_slip', 'Bank Slip'), ('wallet', 'Wallet')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Payment Pending'), ('processing', 'Payment Processing'), ('authorized', 'Payment Authorized'), ('captured', 'Payment Captured'), ('failed', 'Payment Failed'), ('cancelled', 'Payment Cancelled'), ('partially_refunded', 'Payment Partially Refunded'), ('refunded', 'Payment Refunded')], db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('gateway_name', models.CharField(blank=True, max_length=50)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('gateway_customer_id', models.CharField(blank=True, max_length=120)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.payment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('partially_refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle', to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Refund Pending'), ('processed', 'Refund Processed'), ('failed', 'Refund Failed'), ('cancelled', 'Refund Cancelled')], db_index=True, max_length=32)),
                ('gateway_refund_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payment_refunds', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payment_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('authorization', 'Authorization'), ('capture', 'Capture'), ('charge', 'Charge'), ('refund', 'Refund'), ('partial_refund', 'Partial Refund'), ('cancellation', 'Cancellation'), ('failure', 'Failure')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Transaction Pending'), ('success', 'Transaction Succes'), ('failed', 'Transaction Failed'), ('cancelled', 'Transaction Cancelled')], db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('gateway_response_code', models.CharField(blank=True, max_length=64)),
                ('gateway_response_message', models.TextField(blank=True)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'created_at'], name='payment_customer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method'], name='payment_method_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['payment', 'created_at'], name='payrf_pay_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['status'], name='payrf_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment', 'created_at'], name='paymenttx_payment_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_type', 'status'], name='paymenttx_type_status_idx'),
        ),
    ]
