# Generated by Django 6.0.2 on 2026-03-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PHONE', 'Phone'), ('EARPHONE', 'Earphone'), ('HEADSET', 'Headset'), ('MOUSE', 'Mouse'), ('KEYBOARD', 'Keyboard'), ('MICROPHONE', 'Microphone')], db_index=True, max_length=20),
        ),
    ]
