# Generated by Django 6.0.2 on 2026-03-11 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producteventlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='producteventlog',
            new_name='prod_evt_prod_created_idx',
            old_name='product_event_product_created_idx',
        ),
    ]
