# Generated by Django 6.0.2 on 2026-04-01 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_event_product_created_idx_prod_evt_prod_created_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='idempotency_request_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['idempotency_key'], name='product_idempotency_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['idempotency_request_hash'], name='product_idem_hash_idx'),
        ),
    ]
