# Generated by Django 6.0.2 on 2026-04-04 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(db_index=True, help_text='Business-level notification type (example: order_shipped, payment_captured).', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'In-App + Email')], db_index=True, default='in_app', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=16)),
                ('source_module', models.CharField(blank=True, db_index=True, help_text='Origin module of the notification (example: orders, payments, shipping).', max_length=50)),
                ('source_event', models.CharField(blank=True, db_index=True, help_text='Origin event name that triggered the notification.', max_length=100)),
                ('source_object_id', models.CharField(blank=True, db_index=True, help_text='Identifier of the related source object. Stored as text for flexibility.', max_length=64)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='Optional future datetime for deferred dispatch.', null=True)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, help_text='Flexible context payload used for rendering, auditing, or integrations.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32)),
                ('provider_name', models.CharField(blank=True, help_text='Logical provider used for the delivery attempt (example: email_provider, in_app_provider).', max_length=50)),
                ('recipient_address', models.CharField(blank=True, help_text='Resolved delivery destination such as email address when applicable.', max_length=255)),
                ('external_message_id', models.CharField(blank=True, db_index=True, help_text='Optional external provider message identifier.', max_length=120)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('notification_created', 'Notification Created'), ('notification_dispatched', 'Notification Dispatched'), ('notification_read', 'Notification Read'), ('notification_archived', 'Notification Archived'), ('notification_cancelled', 'Notification Cancelled'), ('notification_failed', 'Notification Failed'), ('notification_delivery_sent', 'Notification Delivery Sent'), ('notification_delivery_failed', 'Notification Delivery Failed')], db_index=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notifications.notification')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_notification_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle', to='notifications.notification')),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='not_rec_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='not_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel'], name='not_chan_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='not_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['source_module', 'source_object_id'], name='not_src_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification', 'created_at'], name='notdel_not_cre_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['channel', 'status'], name='notdel_ch_st_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['notification', 'created_at'], name='notevt_not_cre_idx'),
        ),
    ]
