# Generated by Django 6.0.2 on 2026-04-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='event_type',
            field=models.CharField(choices=[('notification_created', 'Notification Created'), ('notification_status_changed', 'Notification Status Changed'), ('notification_dispatched', 'Notification Dispatched'), ('notification_read', 'Notification Read'), ('notification_archived', 'Notification Archived'), ('notification_cancelled', 'Notification Cancelled'), ('notification_failed', 'Notification Failed'), ('notification_delivery_sent', 'Notification Delivery Sent'), ('notification_delivery_failed', 'Notification Delivery Failed')], db_index=True, max_length=100),
        ),
    ]
