# ==============================
# CACHE PREFIXES
# ==============================

ADMIN_DASHBOARD_CACHE_PREFIX = "admin_dashboard"

ADMIN_DASHBOARD_CACHE_MANAGEMENT_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:management"
)


# ==============================
# CACHE VERSION PREFIXES
# ==============================

ADMIN_DASHBOARD_CACHE_VERSION_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:version"
)

ADMIN_DASHBOARD_SUMMARY_VERSION_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_VERSION_PREFIX}:summary"
)

ADMIN_DASHBOARD_OPERATIONAL_METRICS_VERSION_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_VERSION_PREFIX}:operational_metrics"
)

ADMIN_DASHBOARD_ACTIVITY_VERSION_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_VERSION_PREFIX}:activity"
)

ADMIN_DASHBOARD_ALERT_VERSION_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_VERSION_PREFIX}:alerts"
)

ADMIN_DASHBOARD_ORDER_OPERATIONS_VERSION_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_VERSION_PREFIX}:order_operations"
)

ADMIN_DASHBOARD_REVIEW_OPERATIONS_VERSION_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_VERSION_PREFIX}:review_operations"
)

ADMIN_DASHBOARD_NOTIFICATION_OPERATIONS_VERSION_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_VERSION_PREFIX}:notification_operations"
)


# ==============================
# CACHE DETAIL PREFIXES
# ==============================

ADMIN_DASHBOARD_CACHE_DETAIL_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:detail"
)

ADMIN_DASHBOARD_OPERATION_DETAIL_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:operation:detail"
)


# ==============================
# CACHE LIST PREFIXES
# ==============================

ADMIN_DASHBOARD_CACHE_LIST_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:list"
)

ADMIN_DASHBOARD_ACTIVITY_LIST_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:activity:list"
)

ADMIN_DASHBOARD_ALERT_LIST_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:alerts:list"
)

ADMIN_DASHBOARD_ORDER_OPERATION_LIST_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:orders:list"
)

ADMIN_DASHBOARD_REVIEW_OPERATION_LIST_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:reviews:list"
)

ADMIN_DASHBOARD_NOTIFICATION_OPERATION_LIST_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:notifications:list"
)


# ==============================
# CACHE DASHBOARD PREFIXES
# ==============================

ADMIN_DASHBOARD_SUMMARY_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:summary"
)

ADMIN_DASHBOARD_OPERATIONAL_METRICS_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:operational_metrics"
)

ADMIN_DASHBOARD_RECENT_ACTIVITY_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:recent_activity"
)

ADMIN_DASHBOARD_ALERT_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:alerts"
)


# ==============================
# CACHE SEARCH PREFIXES
# ==============================

ADMIN_DASHBOARD_CACHE_SEARCH_PREFIX = (
    f"{ADMIN_DASHBOARD_CACHE_PREFIX}:search"
)


# ==============================
# CACHE TIMEOUTS
# ==============================

ADMIN_DASHBOARD_CACHE_TIMEOUT_SHORT = 60
ADMIN_DASHBOARD_CACHE_TIMEOUT_DEFAULT = 300
ADMIN_DASHBOARD_CACHE_TIMEOUT_LONG = 900


# ==============================
# CACHE VERSION DEFAULTS
# ==============================

ADMIN_DASHBOARD_CACHE_DEFAULT_VERSION = 1