# Generated by Django 6.0.2 on 2026-04-07 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=16)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('orders_pending', models.PositiveIntegerField(default=0)),
                ('orders_processing', models.PositiveIntegerField(default=0)),
                ('orders_shipped', models.PositiveIntegerField(default=0)),
                ('orders_delivered', models.PositiveIntegerField(default=0)),
                ('orders_cancelled', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payments_captured', models.PositiveIntegerField(default=0)),
                ('payments_failed', models.PositiveIntegerField(default=0)),
                ('payments_refunded', models.PositiveIntegerField(default=0)),
                ('shipments_in_transit', models.PositiveIntegerField(default=0)),
                ('shipments_delivered', models.PositiveIntegerField(default=0)),
                ('shipments_failed', models.PositiveIntegerField(default=0)),
                ('products_sold', models.PositiveIntegerField(default=0)),
                ('top_product_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('active_customers', models.PositiveIntegerField(default=0)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_analytics_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('snapshot_created', 'snapshot_created'), ('snapshot_generation_started', 'snapshot_generation_started'), ('snapshot_generation_completed', 'snapshot_generation_completed'), ('snapshot_refreshed', 'snapshot_refreshed'), ('snapshot_failed', 'snapshot_failed')], db_index=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.analyticssnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshotLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle', to='analytics.analyticssnapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['period_type', 'period_start'], name='analytic_period_start_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['period_type', 'period_end'], name='analytic_period_end_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['period_start', 'period_end'], name='analytic_period_range_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['generated_by'], name='analytic_generated_by_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['idempotency_key'], name='analytic_idempotency_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['top_product_id'], name='analytic_top_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticssnapshot',
            constraint=models.UniqueConstraint(fields=('period_type', 'period_start', 'period_end'), name='unique_analytics_snapshot_period'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['snapshot', 'created_at'], name='analyticevent_snapshot_created_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type'], name='analyticevent_type_idx'),
        ),
    ]
