# Generated by Django 6.0.2 on 2026-04-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analyticevent_ss_created_idx',
            old_name='analyticevent_snapshot_created_idx',
        ),
    ]
