# Generated by Django 6.0.2 on 2026-04-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_analyticevent_snapshot_created_idx_analyticevent_ss_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssnapshot',
            name='active_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='approved_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='cancelled_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='confirmed_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='customer_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='hidden_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='high_rated_products_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='inactive_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='low_rated_products_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='rejected_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='staff_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='total_registered_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='unconfirmed_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='verified_purchase_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
