# Generated by Django 6.0.2 on 2026-03-03 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('token_type', models.CharField(choices=[('email_confirmation', 'Email Confirmation'), ('password_reset', 'Password Reset'), ('magic_login', 'Magic Login'), ('invitation', 'Invitation'), ('email_change', 'Email Change'), ('two_factor', 'Two Factor Authentication')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tokens',
            },
        ),
        migrations.DeleteModel(
            name='EmailConfirmationToken',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['token'], name='user_tokens_token_f22396_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['token_type'], name='user_tokens_token_t_49b183_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['user', 'token_type'], name='user_tokens_user_id_f56e54_idx'),
        ),
    ]
