# Generated by Django 6.0.2 on 2026-03-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_remove_passwordresettoken_user_usertoken_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_email'], name='users_custo_user_em_e3dbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_role'], name='users_custo_user_ro_8c352c_idx'),
        ),
    ]
