# Generated by Django 6.0.2 on 2026-03-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_users_custo_user_em_e3dbd6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('customer_user', 'CustomerUser'), ('support_staff', 'SupportStaff'), ('operations_staff', 'OperationsStaff'), ('payment_staff', 'PaymentStaff'), ('admin', 'ADMIN'), ('superadmin', 'SuperADMIN')], db_index=True, default='customer_user', max_length=30),
        ),
    ]
