# Generated by Django 6.0.2 on 2026-04-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_customuser_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['idempotency_key'], name='users_custo_idempot_ff97e8_idx'),
        ),
    ]
