# Generated by Django 6.0.2 on 2026-04-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_customuser_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='idempotency_request_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['idempotency_request_hash'], name='users_custo_idempot_d9c0cc_idx'),
        ),
    ]
