# Generated by Django 6.0.2 on 2026-04-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_idempotency_request_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('customer_user', 'CustomerUser'), ('analytics_staff', 'AnalyticsStaff'), ('support_staff', 'SupportStaff'), ('operations_staff', 'OperationsStaff'), ('payment_staff', 'PaymentStaff'), ('admin', 'ADMIN'), ('superadmin', 'SuperADMIN')], db_index=True, default='customer_user', max_length=30),
        ),
    ]
