from ech.users.constants.constants import (
    LABEL_SUPERADMIN,
    LABEL_ADMIN,
    LABEL_PAYMENT_STAFF,
    LABEL_OPERATIONS_STAFF,
    LABEL_SUPPORT_STAFF,
    LABEL_CUSTOMER_USER,
)


"""
Roles choices constants for models.py.

"""


ROLE_SUPERADMIN = "superadmin"
ROLE_ADMIN = "admin"
ROLE_PAYMENT_STAFF = "payment_staff"
ROLE_OPERATIONS_STAFF = "operations_staff"
ROLE_SUPPORT_STAFF = "support_staff"
ROLE_CUSTOMER_USER = "customer_user"

ROLE_CHOICES = [
    (ROLE_CUSTOMER_USER, LABEL_CUSTOMER_USER),
    (ROLE_SUPPORT_STAFF, LABEL_SUPPORT_STAFF),
    (ROLE_OPERATIONS_STAFF, LABEL_OPERATIONS_STAFF),
    (ROLE_PAYMENT_STAFF, LABEL_PAYMENT_STAFF),
    (ROLE_ADMIN, LABEL_ADMIN),
    (ROLE_SUPERADMIN, LABEL_SUPERADMIN),
]
