from ech.users.constants.constants import (
    LABEL_TOKEN_TYPE_EMAIL_CONFIRMATION,
    LABEL_TOKEN_TYPE_PASSWORD_RESET,
    LABEL_TOKEN_TYPE_MAGIC_LOGIN,
    LABEL_TOKEN_TYPE_INVITATION,
    LABEL_TOKEN_TYPE_EMAIL_CHANGE,
    LABEL_TOKEN_TYPE_2FA,
)


"""
Tokens choices constants for models.py.

"""


TYPE_EMAIL_CONFIRMATION = "email_confirmation"
TYPE_PASSWORD_RESET = "password_reset"
TYPE_MAGIC_LOGIN = "magic_login"
TYPE_INVITATION = "invitation"
TYPE_EMAIL_CHANGE = "email_change"
TYPE_2FA = "two_factor"

TOKEN_TYPE_CHOICES = [
    (TYPE_EMAIL_CONFIRMATION, LABEL_TOKEN_TYPE_EMAIL_CONFIRMATION),
    (TYPE_PASSWORD_RESET, LABEL_TOKEN_TYPE_PASSWORD_RESET),
    (TYPE_MAGIC_LOGIN, LABEL_TOKEN_TYPE_MAGIC_LOGIN),
    (TYPE_INVITATION, LABEL_TOKEN_TYPE_INVITATION),
    (TYPE_EMAIL_CHANGE, LABEL_TOKEN_TYPE_EMAIL_CHANGE),
    (TYPE_2FA, LABEL_TOKEN_TYPE_2FA),
]