# Generated by Django 6.0.2 on 2026-04-11 21:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_index=True, max_length=120)),
                ('target_object_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('target_module', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_dashboard_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminDashboardLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle', to='admin_dashboard.admindashboardlog')),
            ],
        ),
        migrations.CreateModel(
            name='AdminDashboardEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('dashboard_viewed', 'dashboard_viewed'), ('dashboard_summary_fetched', 'dashboard_summary_fetched'), ('dashboard_operational_metrics_fetched', 'dashboard_operational_metrics_fetched'), ('dashboard_recent_activity_fetched', 'dashboard_recent_activity_fetched'), ('order_bulk_action_executed', 'order_bulk_action_executed'), ('review_bulk_moderation_executed', 'review_bulk_moderation_executed'), ('notification_retry_executed', 'notification_retry_executed'), ('operational_alert_triggered', 'operational_alert_triggered')], db_index=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_dashboard_events', to=settings.AUTH_USER_MODEL)),
                ('related_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='admin_dashboard.admindashboardlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='admindashboardlog',
            index=models.Index(fields=['action_type'], name='adminlog_action_type_idx'),
        ),
        migrations.AddIndex(
            model_name='admindashboardlog',
            index=models.Index(fields=['performed_by'], name='adminlog_performed_by_idx'),
        ),
        migrations.AddIndex(
            model_name='admindashboardlog',
            index=models.Index(fields=['target_module'], name='adminlog_target_module_idx'),
        ),
        migrations.AddIndex(
            model_name='admindashboardlog',
            index=models.Index(fields=['created_at'], name='adminlog_created_idx'),
        ),
        migrations.AddIndex(
            model_name='admindashboardevent',
            index=models.Index(fields=['event_type'], name='admindash_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='admindashboardevent',
            index=models.Index(fields=['created_at'], name='admindash_event_created_idx'),
        ),
    ]
