# =========================
# CACHE INPUTS
# =========================

SHIPPING_DETAIL_CACHE_TIMEOUT = 60 * 5

SHIPPING_MANAGEMENT_DETAIL_CACHE_TIMEOUT = 60 * 3

CUSTOMER_SHIPPING_LIST_CACHE_TIMEOUT = 60 * 2

MANAGEMENT_SHIPPING_LIST_CACHE_TIMEOUT = 60