# =============================
# CACHE PREFIXES
# =============================

SHIPPING_CACHE_PREFIX = "shipping"

SHIPPING_CACHE_VERSION_PREFIX = f"{SHIPPING_CACHE_PREFIX}:version"
SHIPPING_CACHE_DETAIL_PREFIX = f"{SHIPPING_CACHE_PREFIX}:detail"
SHIPPING_CACHE_ORDER_LOOKUP_PREFIX = f"{SHIPPING_CACHE_PREFIX}:order"
SHIPPING_CACHE_CUSTOMER_PREFIX = f"{SHIPPING_CACHE_PREFIX}:customer"
SHIPPING_CACHE_MANAGEMENT_PREFIX = f"{SHIPPING_CACHE_PREFIX}:management"
SHIPPING_CACHE_SEARCH_PREFIX = f"{SHIPPING_CACHE_PREFIX}:search"

# =============================
# CACHE TIMEOUTS
# =============================

SHIPPING_CACHE_TIMEOUT_SHORT = 60
SHIPPING_CACHE_TIMEOUT_DEFAULT = 300
SHIPPING_CACHE_TIMEOUT_LONG = 900

# =============================
# CACHE VERSION DEFAULTS
# =============================

SHIPPING_CACHE_DEFAULT_VERSION = 1