# =========================
# CACHE INPUTS
# =========================

ORDER_DETAIL_CACHE_TIMEOUT = 60 * 5

ORDER_MANAGEMENT_DETAIL_CACHE_TIMEOUT = 60 * 3

CUSTOMER_ORDERS_LIST_CACHE_TIMEOUT = 60 * 2

MANAGEMENT_ORDERS_LIST_CACHE_TIMEOUT = 60